<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.433">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>practica-laura-aparicio</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="Practica-Laura Aparicio_files/libs/clipboard/clipboard.min.js"></script>
<script src="Practica-Laura Aparicio_files/libs/quarto-html/quarto.js"></script>
<script src="Practica-Laura Aparicio_files/libs/quarto-html/popper.min.js"></script>
<script src="Practica-Laura Aparicio_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="Practica-Laura Aparicio_files/libs/quarto-html/anchor.min.js"></script>
<link href="Practica-Laura Aparicio_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="Practica-Laura Aparicio_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="Practica-Laura Aparicio_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="Practica-Laura Aparicio_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="Practica-Laura Aparicio_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">


</head>

<body class="fullcontent">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">

<main class="content" id="quarto-document-content">



<p>Vasmos a cargar el dataset de AirBnB descargado de <a href="https://public.opendatasoft.com/explore/dataset/airbnb-listings/export/?disjunctive.host_verifications&amp;disjunctive.amenities&amp;disjunctive.features&amp;q=Madrid&amp;dataChart=eyJxdWVyaWVzIjpbeyJjaGFydHMiOlt7InR5cGUiOiJjb2x1bW4iLCJmdW5jIjoiQ09VTlQiLCJ5QXhpcyI6Imhvc3RfbGlzdGluZ3NfY291bnQiLCJzY2llbnRpZmljRGlzcGxheSI6dHJ1ZSwiY29sb3IiOiJyYW5nZS1jdXN0b20ifV0sInhBeGlzIjoiY2l0eSIsIm1heHBvaW50cyI6IiIsInRpbWVzY2FsZSI6IiIsInNvcnQiOiIiLCJzZXJpZXNCcmVha2Rvd24iOiJyb29tX3R5cGUiLCJjb25maWciOnsiZGF0YXNldCI6ImFpcmJuYi1saXN0aW5ncyIsIm9wdGlvbnMiOnsiZGlzanVuY3RpdmUuaG9zdF92ZXJpZmljYXRpb25zIjp0cnVlLCJkaXNqdW5jdGl2ZS5hbWVuaXRpZXMiOnRydWUsImRpc2p1bmN0aXZlLmZlYXR1cmVzIjp0cnVlfX19XSwidGltZXNjYWxlIjoiIiwiZGlzcGxheUxlZ2VuZCI6dHJ1ZSwiYWxpZ25Nb250aCI6dHJ1ZX0%3D&amp;location=16,41.38377,2.15774&amp;basemap=jawg.streets">aquí</a></p>
<p><img src="descargar.png" class="img-fluid"></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a>airbnb<span class="ot">&lt;-</span><span class="fu">read.csv</span>(<span class="st">'airbnb-listings.csv'</span>,<span class="at">sep =</span> <span class="st">';'</span>)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">options</span>(<span class="at">repr.plot.height=</span><span class="dv">4</span>,<span class="at">repr.plot.width=</span><span class="dv">6</span>,<span class="at">repr.plot.res =</span> <span class="dv">300</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<ol type="1">
<li>Vamos a quedarnos con las columnas de mayor interés: ‘City’,‘Room.Type’,‘Neighbourhood’,‘Accommodates’,‘Bathrooms’,‘Bedrooms’,‘Beds’,‘Price’,‘Square.Feet’,‘Guests.Included’,‘Extra.People’,‘Review.Scores.Rating’,‘Latitude’, ‘Longitude’ Nos quedarmos solo con las entradas de Madrid para Room.Type==“Entire home/apt” y cuyo barrio (Neighbourhood) no está vacio ’’ Podemos eliminar las siguientes columnas que ya no son necesarias: “Room.Type”,‘City’ Llama a nuevo dataframe df_madrid.</li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="co">#  Nos quedarmos solo con las entradas de Madrid para Room.Type=="Entire home/apt" y cuyo barrio (Neighbourhood) no está vacio</span></span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a>df_madrid <span class="ot">&lt;-</span> airbnb[<span class="fu">grepl</span>(<span class="st">"Madrid"</span>, airbnb<span class="sc">$</span>City, <span class="at">ignore.case =</span> <span class="cn">TRUE</span>) <span class="sc">&amp;</span></span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a>             airbnb<span class="sc">$</span>Room.Type <span class="sc">==</span> <span class="st">"Entire home/apt"</span> <span class="sc">&amp;</span></span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a>             airbnb<span class="sc">$</span>Neighbourhood <span class="sc">!=</span> <span class="st">""</span>, ]</span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-6"><a href="#cb2-6" aria-hidden="true" tabindex="-1"></a><span class="co"># Vamos a quedarnos con las columnas de mayor interés</span></span>
<span id="cb2-7"><a href="#cb2-7" aria-hidden="true" tabindex="-1"></a>df_madrid <span class="ot">&lt;-</span> df_madrid[, <span class="fu">c</span>(<span class="st">'City'</span>,<span class="st">'Room.Type'</span>,<span class="st">'Neighbourhood'</span>,<span class="st">'Accommodates'</span>,<span class="st">'Bathrooms'</span>,<span class="st">'Bedrooms'</span>,<span class="st">'Beds'</span>,<span class="st">'Price'</span>,<span class="st">'Square.Feet'</span>,<span class="st">'Guests.Included'</span>,<span class="st">'Extra.People'</span>,<span class="st">'Review.Scores.Rating'</span>,<span class="st">'Latitude'</span>, <span class="st">'Longitude'</span>)]</span>
<span id="cb2-8"><a href="#cb2-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-9"><a href="#cb2-9" aria-hidden="true" tabindex="-1"></a><span class="co"># Podemos eliminar las siguientes columnas que ya no son necesarias: "Room.Type",'City'</span></span>
<span id="cb2-10"><a href="#cb2-10" aria-hidden="true" tabindex="-1"></a>df_madrid <span class="ot">&lt;-</span> df_madrid[, <span class="sc">!</span>(<span class="fu">names</span>(df_madrid) <span class="sc">%in%</span> <span class="fu">c</span>(<span class="st">"Room.Type"</span>, <span class="st">"City"</span>))]</span>
<span id="cb2-11"><a href="#cb2-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-12"><a href="#cb2-12" aria-hidden="true" tabindex="-1"></a><span class="co"># Resultado</span></span>
<span id="cb2-13"><a href="#cb2-13" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(df_madrid)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   Neighbourhood Accommodates Bathrooms Bedrooms Beds Price Square.Feet
3         Cortes            2         1        1    1    75          NA
10     Recoletos            3         1        1    1   106          NA
11      Malasaña            2         1        1    1    52          NA
12          Goya            3         1        0    2    40          NA
14      San Blas            4         1        1    1    50          NA
17       Palacio            4         1        1    2    82          NA
   Guests.Included Extra.People Review.Scores.Rating Latitude Longitude
3                1            0                   80 40.41362 -3.697618
10               1            0                   NA 40.42255 -3.689689
11               2           25                   92 40.42576 -3.707467
12               2           15                   92 40.42607 -3.677779
14               1            0                  100 40.43657 -3.618870
17               2            0                   95 40.41797 -3.709786</code></pre>
</div>
</div>
<hr>
<ol start="2" type="1">
<li>Crea una nueva columna llamada Square.Meters a partir de Square.Feet. Recuerda que un pie cuadrado son 0.092903 metros cuadrados.</li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Crea una nueva columna llamada Square.Meters a partir de Square.Feet</span></span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a>df_madrid<span class="sc">$</span>Square.Meters <span class="ot">&lt;-</span> df_madrid<span class="sc">$</span>Square.Feet <span class="sc">*</span> <span class="fl">0.092903</span></span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Resultado</span></span>
<span id="cb4-5"><a href="#cb4-5" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(df_madrid)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   Neighbourhood Accommodates Bathrooms Bedrooms Beds Price Square.Feet
3         Cortes            2         1        1    1    75          NA
10     Recoletos            3         1        1    1   106          NA
11      Malasaña            2         1        1    1    52          NA
12          Goya            3         1        0    2    40          NA
14      San Blas            4         1        1    1    50          NA
17       Palacio            4         1        1    2    82          NA
   Guests.Included Extra.People Review.Scores.Rating Latitude Longitude
3                1            0                   80 40.41362 -3.697618
10               1            0                   NA 40.42255 -3.689689
11               2           25                   92 40.42576 -3.707467
12               2           15                   92 40.42607 -3.677779
14               1            0                  100 40.43657 -3.618870
17               2            0                   95 40.41797 -3.709786
   Square.Meters
3             NA
10            NA
11            NA
12            NA
14            NA
17            NA</code></pre>
</div>
</div>
<hr>
<ol start="3" type="1">
<li>¿Que porcentaje de los apartamentos no muestran los metros cuadrados? Es decir, ¿cuantos tienen NA en Square.Meters?</li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Total de apartamentos</span></span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a>total_apartamentos <span class="ot">&lt;-</span> <span class="fu">nrow</span>(df_madrid)</span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"Total de apartamentos:"</span>, total_apartamentos, <span class="st">"</span><span class="sc">\n\n</span><span class="st">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Total de apartamentos: 5608 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Apartamentos sin valores en Square.Meters</span></span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a>apartamentos_sin_metros_cuadrados <span class="ot">&lt;-</span> <span class="fu">sum</span>(<span class="fu">is.na</span>(df_madrid<span class="sc">$</span>Square.Meters))</span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"Apartamentos sin metros cuadrados:"</span>, apartamentos_sin_metros_cuadrados, <span class="st">"</span><span class="sc">\n\n</span><span class="st">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Apartamentos sin metros cuadrados: 5261 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Porcentaje</span></span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a>porcentaje_faltantes <span class="ot">&lt;-</span> (apartamentos_sin_metros_cuadrados <span class="sc">/</span> total_apartamentos) <span class="sc">*</span> <span class="dv">100</span></span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"Porcentaje de apartamentos sin metros cuadrados:"</span>, <span class="fu">round</span>(porcentaje_faltantes, <span class="dv">2</span>), <span class="st">"%</span><span class="sc">\n</span><span class="st">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Porcentaje de apartamentos sin metros cuadrados: 93.81 %</code></pre>
</div>
</div>
<hr>
<ol start="4" type="1">
<li>De todos los apartamentos que tienen un valor de metros cuadrados diferente de NA ¿Que porcentaje de los apartamentos tienen 0 metros cuadrados?</li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Apartamentos con valores en Square.Meters</span></span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a>total_apartamentos_con_metros_cuadrados <span class="ot">=</span> <span class="fu">sum</span>(<span class="sc">!</span><span class="fu">is.na</span>(df_madrid<span class="sc">$</span>Square.Meters))</span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"Apartamentos con metros cuadrados:"</span>, total_apartamentos_con_metros_cuadrados, <span class="st">"</span><span class="sc">\n\n</span><span class="st">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Apartamentos con metros cuadrados: 347 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Apartamentos 0 metros cuadrados</span></span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a>apartamentos_con_cero_metros_cuadrados <span class="ot">=</span> <span class="fu">sum</span>(<span class="sc">!</span><span class="fu">is.na</span>(df_madrid<span class="sc">$</span>Square.Meters) <span class="sc">&amp;</span> df_madrid<span class="sc">$</span>Square.Meters <span class="sc">==</span> <span class="dv">0</span>)</span>
<span id="cb14-3"><a href="#cb14-3" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"Apartamentos con cero metros cuadrados:"</span>, apartamentos_con_cero_metros_cuadrados, <span class="st">"</span><span class="sc">\n\n</span><span class="st">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Apartamentos con cero metros cuadrados: 128 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Porcentaje</span></span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a>porcentaje_cero_metros_cuadrados <span class="ot">=</span> (apartamentos_con_cero_metros_cuadrados <span class="sc">/</span> total_apartamentos_con_metros_cuadrados) <span class="sc">*</span> <span class="dv">100</span></span>
<span id="cb16-3"><a href="#cb16-3" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"Porcentaje de apartamentos con 0 metros cuadrados:"</span>, <span class="fu">round</span>(porcentaje_cero_metros_cuadrados, <span class="dv">2</span>), <span class="st">"%</span><span class="sc">\n</span><span class="st">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Porcentaje de apartamentos con 0 metros cuadrados: 36.89 %</code></pre>
</div>
</div>
<hr>
<ol start="5" type="1">
<li>Reemplazar todos los 0m^2 por NA</li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Reemplaza los valores de 0 metros cuadrados por NA</span></span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a>df_madrid<span class="sc">$</span>Square.Meters[df_madrid<span class="sc">$</span>Square.Meters <span class="sc">==</span> <span class="dv">0</span>] <span class="ot">&lt;-</span> <span class="cn">NA</span></span>
<span id="cb18-3"><a href="#cb18-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-4"><a href="#cb18-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Resultado</span></span>
<span id="cb18-5"><a href="#cb18-5" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(df_madrid)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   Neighbourhood Accommodates Bathrooms Bedrooms Beds Price Square.Feet
3         Cortes            2         1        1    1    75          NA
10     Recoletos            3         1        1    1   106          NA
11      Malasaña            2         1        1    1    52          NA
12          Goya            3         1        0    2    40          NA
14      San Blas            4         1        1    1    50          NA
17       Palacio            4         1        1    2    82          NA
   Guests.Included Extra.People Review.Scores.Rating Latitude Longitude
3                1            0                   80 40.41362 -3.697618
10               1            0                   NA 40.42255 -3.689689
11               2           25                   92 40.42576 -3.707467
12               2           15                   92 40.42607 -3.677779
14               1            0                  100 40.43657 -3.618870
17               2            0                   95 40.41797 -3.709786
   Square.Meters
3             NA
10            NA
11            NA
12            NA
14            NA
17            NA</code></pre>
</div>
</div>
<hr>
<p>Hay muchos NAs, vamos a intentar crear un modelo que nos prediga cuantos son los metros cuadrados en función del resto de variables para tratar de rellenar esos NA. Pero <strong>antes de crear el modelo</strong> vamos a hacer: * pintar el histograma de los metros cuadrados y ver si tenemos que filtrar algún elemento más. * crear una variable sintética nueva basada en la similitud entre barrios que usaremos en nuestro modelo.</p>
<ol start="6" type="1">
<li>Pinta el histograma de los metros cuadrados y ver si tenemos que filtrar algún elemento más</li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-3"><a href="#cb20-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Histograma</span></span>
<span id="cb20-4"><a href="#cb20-4" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(df_madrid, <span class="fu">aes</span>(<span class="at">x =</span> Square.Meters)) <span class="sc">+</span></span>
<span id="cb20-5"><a href="#cb20-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="at">binwidth =</span> <span class="dv">5</span>, <span class="at">fill =</span> <span class="st">"skyblue"</span>, <span class="at">color =</span> <span class="st">"black"</span>) <span class="sc">+</span></span>
<span id="cb20-6"><a href="#cb20-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Histograma de Metros Cuadrados en AirBnB Madrid"</span>,</span>
<span id="cb20-7"><a href="#cb20-7" aria-hidden="true" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">"Metros Cuadrados"</span>,</span>
<span id="cb20-8"><a href="#cb20-8" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">"Frecuencia"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Removed 5389 rows containing non-finite values (`stat_bin()`).</code></pre>
</div>
<div class="cell-output-display">
<p><img src="Practica-Laura-Aparicio_files/figure-html/unnamed-chunk-7-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Hay apartamentos con tamaños muy pequeños (menos de 20m2), lo que podría considerarse como valores atípicos. Estos valores podrían ser apartamentos tipo estudio o habitaciones más pequeñas. También hay apartamentos con tamaños iguales o superiores a unos200m2.</p>
<hr>
<ol start="7" type="1">
<li>Asigna el valor NA a la columna Square.Meters de los apartamentos que tengan menos de 20 m^2</li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Asigna el valor NA a los apartamentos de menos de 20 metros cuadrados</span></span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a>df_madrid<span class="sc">$</span>Square.Meters[df_madrid<span class="sc">$</span>Square.Meters <span class="sc">&lt;</span> <span class="dv">20</span>] <span class="ot">&lt;-</span> <span class="cn">NA</span></span>
<span id="cb22-3"><a href="#cb22-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-4"><a href="#cb22-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Modifico también los valores mayores a 175m2</span></span>
<span id="cb22-5"><a href="#cb22-5" aria-hidden="true" tabindex="-1"></a>df_madrid<span class="sc">$</span>Square.Meters[df_madrid<span class="sc">$</span>Square.Meters <span class="sc">&gt;</span> <span class="dv">175</span>] <span class="ot">&lt;-</span> <span class="cn">NA</span></span>
<span id="cb22-6"><a href="#cb22-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-7"><a href="#cb22-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Resultado</span></span>
<span id="cb22-8"><a href="#cb22-8" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(df_madrid)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   Neighbourhood Accommodates Bathrooms Bedrooms Beds Price Square.Feet
3         Cortes            2         1        1    1    75          NA
10     Recoletos            3         1        1    1   106          NA
11      Malasaña            2         1        1    1    52          NA
12          Goya            3         1        0    2    40          NA
14      San Blas            4         1        1    1    50          NA
17       Palacio            4         1        1    2    82          NA
   Guests.Included Extra.People Review.Scores.Rating Latitude Longitude
3                1            0                   80 40.41362 -3.697618
10               1            0                   NA 40.42255 -3.689689
11               2           25                   92 40.42576 -3.707467
12               2           15                   92 40.42607 -3.677779
14               1            0                  100 40.43657 -3.618870
17               2            0                   95 40.41797 -3.709786
   Square.Meters
3             NA
10            NA
11            NA
12            NA
14            NA
17            NA</code></pre>
</div>
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Histograma actualizado</span></span>
<span id="cb24-2"><a href="#cb24-2" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(df_madrid, <span class="fu">aes</span>(<span class="at">x =</span> Square.Meters)) <span class="sc">+</span></span>
<span id="cb24-3"><a href="#cb24-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="at">binwidth =</span> <span class="dv">5</span>, <span class="at">fill =</span> <span class="st">"skyblue"</span>, <span class="at">color =</span> <span class="st">"black"</span>) <span class="sc">+</span></span>
<span id="cb24-4"><a href="#cb24-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Histograma de Metros Cuadrados en AirBnB Madrid"</span>,</span>
<span id="cb24-5"><a href="#cb24-5" aria-hidden="true" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">"Metros Cuadrados"</span>,</span>
<span id="cb24-6"><a href="#cb24-6" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">"Frecuencia"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Removed 5438 rows containing non-finite values (`stat_bin()`).</code></pre>
</div>
<div class="cell-output-display">
<p><img src="Practica-Laura-Aparicio_files/figure-html/unnamed-chunk-8-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<hr>
<ol start="8" type="1">
<li>Existen varios Barrios que todas sus entradas de Square.Meters son NA, vamos a eliminar del dataset todos los pisos que pertenecen a estos barrios.</li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>
Attaching package: 'dplyr'</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>The following objects are masked from 'package:stats':

    filter, lag</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>The following objects are masked from 'package:base':

    intersect, setdiff, setequal, union</code></pre>
</div>
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a>total_apartamentos <span class="ot">&lt;-</span> <span class="fu">summarise</span>(<span class="fu">group_by</span>(df_madrid, Neighbourhood), <span class="at">total_apartamentos =</span> <span class="fu">n</span>())</span>
<span id="cb30-2"><a href="#cb30-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-3"><a href="#cb30-3" aria-hidden="true" tabindex="-1"></a>apartamentos_con_na <span class="ot">&lt;-</span> <span class="fu">summarise</span>(<span class="fu">group_by</span>(df_madrid, Neighbourhood), <span class="at">apartamentos_con_na =</span> <span class="fu">sum</span>(<span class="fu">is.na</span>(Square.Meters)))</span>
<span id="cb30-4"><a href="#cb30-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-5"><a href="#cb30-5" aria-hidden="true" tabindex="-1"></a>join <span class="ot">&lt;-</span> <span class="fu">left_join</span>(total_apartamentos, apartamentos_con_na, <span class="at">by =</span> <span class="st">"Neighbourhood"</span>)</span>
<span id="cb30-6"><a href="#cb30-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-7"><a href="#cb30-7" aria-hidden="true" tabindex="-1"></a>barrios_a_excluir <span class="ot">&lt;-</span> join<span class="sc">$</span>Neighbourhood[join<span class="sc">$</span>total_apartamentos <span class="sc">==</span> join<span class="sc">$</span>apartamentos_con_na]</span>
<span id="cb30-8"><a href="#cb30-8" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"Barrios a excluir:"</span>, barrios_a_excluir, <span class="st">"</span><span class="sc">\n\n</span><span class="st">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Barrios a excluir: Aluche Arganzuela Atocha Bellas Vistas Berruguete Castillejos Delicias Estrella Fuencarral-El Pardo Fuencarral-el Pardo Gaztambide Guindalera Hispanoamérica Hortaleza Ibiza Imperial La Chopera Legazpi Moncloa Nueva España Prosperidad Puente de Vallecas Rios Rosas Tetuán Valdeacederas Vallehermosa Villa de Vallecas Villaverde </code></pre>
</div>
<div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a>df_madrid <span class="ot">&lt;-</span> <span class="fu">filter</span>(df_madrid, <span class="sc">!</span>(Neighbourhood <span class="sc">%in%</span> barrios_a_excluir))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<hr>
<p>El barrio parece ser un indicador importante para los metros cuadrados de un apartamento.</p>
<p>Vamos a agrupar los barrios por metros cuadrados. Podemos usar una matriz de similaridad de Tukey tal y como hicimos en el curso de estadística:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb33"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a>tky<span class="ot">&lt;-</span><span class="fu">TukeyHSD</span>(<span class="fu">aov</span>( <span class="at">formula=</span>Square.Meters<span class="sc">~</span>Neighbourhood, <span class="at">data=</span>df_madrid ))</span>
<span id="cb33-2"><a href="#cb33-2" aria-hidden="true" tabindex="-1"></a>tky.result<span class="ot">&lt;-</span><span class="fu">data.frame</span>(tky<span class="sc">$</span>Neighbourhood)</span>
<span id="cb33-3"><a href="#cb33-3" aria-hidden="true" tabindex="-1"></a>cn <span class="ot">&lt;-</span><span class="fu">sort</span>(<span class="fu">unique</span>(df_madrid<span class="sc">$</span>Neighbourhood))</span>
<span id="cb33-4"><a href="#cb33-4" aria-hidden="true" tabindex="-1"></a>resm <span class="ot">&lt;-</span> <span class="fu">matrix</span>(<span class="cn">NA</span>, <span class="fu">length</span>(cn),<span class="fu">length</span>(cn))</span>
<span id="cb33-5"><a href="#cb33-5" aria-hidden="true" tabindex="-1"></a><span class="fu">rownames</span>(resm) <span class="ot">&lt;-</span> cn</span>
<span id="cb33-6"><a href="#cb33-6" aria-hidden="true" tabindex="-1"></a><span class="fu">colnames</span>(resm) <span class="ot">&lt;-</span> cn</span>
<span id="cb33-7"><a href="#cb33-7" aria-hidden="true" tabindex="-1"></a>resm[<span class="fu">lower.tri</span>(resm) ] <span class="ot">&lt;-</span> <span class="fu">round</span>(tky.result<span class="sc">$</span>p.adj,<span class="dv">4</span>)</span>
<span id="cb33-8"><a href="#cb33-8" aria-hidden="true" tabindex="-1"></a>resm[<span class="fu">upper.tri</span>(resm) ] <span class="ot">&lt;-</span> <span class="fu">t</span>(resm)[<span class="fu">upper.tri</span>(resm)] </span>
<span id="cb33-9"><a href="#cb33-9" aria-hidden="true" tabindex="-1"></a><span class="fu">diag</span>(resm) <span class="ot">&lt;-</span> <span class="dv">1</span></span>
<span id="cb33-10"><a href="#cb33-10" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb33-11"><a href="#cb33-11" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(reshape2)</span>
<span id="cb33-12"><a href="#cb33-12" aria-hidden="true" tabindex="-1"></a>dfResm <span class="ot">&lt;-</span> <span class="fu">melt</span>(resm)</span>
<span id="cb33-13"><a href="#cb33-13" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(dfResm, <span class="fu">aes</span>(<span class="at">x=</span>Var1, <span class="at">y=</span>Var2, <span class="at">fill=</span>value))<span class="sc">+</span></span>
<span id="cb33-14"><a href="#cb33-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_tile</span>(<span class="at">colour =</span> <span class="st">"black"</span>)<span class="sc">+</span></span>
<span id="cb33-15"><a href="#cb33-15" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_fill_gradient</span>(<span class="at">low =</span> <span class="st">"white"</span>,<span class="at">high =</span> <span class="st">"steelblue"</span>)<span class="sc">+</span></span>
<span id="cb33-16"><a href="#cb33-16" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ylab</span>(<span class="st">"Class"</span>)<span class="sc">+</span><span class="fu">xlab</span>(<span class="st">"Class"</span>)<span class="sc">+</span><span class="fu">theme_bw</span>()<span class="sc">+</span></span>
<span id="cb33-17"><a href="#cb33-17" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">axis.text.x =</span> <span class="fu">element_text</span>(<span class="at">angle =</span> <span class="dv">90</span>, <span class="at">hjust =</span> <span class="dv">1</span>),<span class="at">legend.position=</span><span class="st">"none"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="Practica-Laura-Aparicio_files/figure-html/unnamed-chunk-10-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<ol start="9" type="1">
<li>Usando como variable de distancia: 1-resm Dibuja un dendrograma de los diferentes barrios.</li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb34"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb34-2"><a href="#cb34-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(reshape2)</span>
<span id="cb34-3"><a href="#cb34-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dendextend)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>
---------------------
Welcome to dendextend version 1.17.1
Type citation('dendextend') for how to cite the package.

Type browseVignettes(package = 'dendextend') for the package vignette.
The github page is: https://github.com/talgalili/dendextend/

Suggestions and bug-reports can be submitted at: https://github.com/talgalili/dendextend/issues
You may ask questions at stackoverflow, use the r and dendextend tags: 
     https://stackoverflow.com/questions/tagged/dendextend

    To suppress this message use:  suppressPackageStartupMessages(library(dendextend))
---------------------</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>
Attaching package: 'dendextend'</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>The following object is masked from 'package:stats':

    cutree</code></pre>
</div>
<div class="sourceCode cell-code" id="cb38"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Distancia</span></span>
<span id="cb38-2"><a href="#cb38-2" aria-hidden="true" tabindex="-1"></a>dist <span class="ot">&lt;-</span> <span class="dv">1</span> <span class="sc">-</span> resm</span>
<span id="cb38-3"><a href="#cb38-3" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(dist)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> num [1:37, 1:37] 0 0 0 0 0 0 0 0 0.126 0 ...
 - attr(*, "dimnames")=List of 2
  ..$ : chr [1:37] "Acacias" "Adelfas" "Almagro" "Almenara" ...
  ..$ : chr [1:37] "Acacias" "Adelfas" "Almagro" "Almenara" ...</code></pre>
</div>
<div class="sourceCode cell-code" id="cb40"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb40-1"><a href="#cb40-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Dendrograma</span></span>
<span id="cb40-2"><a href="#cb40-2" aria-hidden="true" tabindex="-1"></a>hc <span class="ot">&lt;-</span> <span class="fu">hclust</span>(<span class="fu">as.dist</span>(dist), <span class="at">method =</span> <span class="st">"complete"</span>)</span>
<span id="cb40-3"><a href="#cb40-3" aria-hidden="true" tabindex="-1"></a>hcd <span class="ot">&lt;-</span> <span class="fu">as.dendrogram</span>(hc)</span>
<span id="cb40-4"><a href="#cb40-4" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(hcd, <span class="at">main =</span> <span class="st">"Dendrograma de Barrios"</span>, <span class="at">xlab =</span> <span class="st">"Barrios"</span>, <span class="at">ylab =</span> <span class="st">"Distancia"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="Practica-Laura-Aparicio_files/figure-html/unnamed-chunk-11-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<hr>
<ol start="10" type="1">
<li>¿Que punto de corte sería el aconsejable?, ¿cuantos clusters aparecen?</li>
</ol>
<p>Se pueden observar dos clústeres principales. Un punto de corte aconsejable podría ser alrededor de 0.6</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb41"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb41-1"><a href="#cb41-1" aria-hidden="true" tabindex="-1"></a>hcd <span class="ot">&lt;-</span> <span class="fu">as.dendrogram</span>(hc)</span>
<span id="cb41-2"><a href="#cb41-2" aria-hidden="true" tabindex="-1"></a>hcd <span class="ot">&lt;-</span> <span class="fu">set</span>(hcd,<span class="st">"labels_cex"</span>, <span class="fl">0.45</span>) </span>
<span id="cb41-3"><a href="#cb41-3" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(<span class="fu">color_branches</span>(hcd,<span class="at">h=</span><span class="fl">0.5</span>),<span class="at">horiz=</span><span class="cn">TRUE</span>,<span class="at">cex=</span><span class="dv">0</span>)</span>
<span id="cb41-4"><a href="#cb41-4" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(<span class="at">v=</span><span class="fl">0.6</span>,<span class="at">col=</span><span class="st">"purple"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="Practica-Laura-Aparicio_files/figure-html/unnamed-chunk-12-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb42"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb42-1"><a href="#cb42-1" aria-hidden="true" tabindex="-1"></a>clusters<span class="ot">&lt;-</span><span class="fu">cutree</span>(hc,<span class="at">h=</span><span class="fl">0.6</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<hr>
<ol start="11" type="1">
<li>Vamos a crear una nueva columna en el dataframe df_madrid con un nuevo identificador marcado por los clusters obtenidos. Esta columna la llamaremos neighb_id</li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb43"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb43-1"><a href="#cb43-1" aria-hidden="true" tabindex="-1"></a>df_clusters<span class="ot">&lt;-</span><span class="fu">data.frame</span>(<span class="at">names=</span><span class="fu">names</span>(clusters),<span class="at">neighb_id=</span><span class="fu">paste0</span>(<span class="st">"Cluster_"</span>,clusters))</span>
<span id="cb43-2"><a href="#cb43-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb43-3"><a href="#cb43-3" aria-hidden="true" tabindex="-1"></a>df_madrid<span class="ot">&lt;-</span><span class="fu">merge</span>(df_madrid,df_clusters,<span class="at">by.x =</span> <span class="st">"Neighbourhood"</span>,<span class="at">by.y=</span><span class="st">'names'</span>)</span>
<span id="cb43-4"><a href="#cb43-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb43-5"><a href="#cb43-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Resultados</span></span>
<span id="cb43-6"><a href="#cb43-6" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(df_clusters,<span class="dv">10</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>         names neighb_id
1      Acacias Cluster_1
2      Adelfas Cluster_1
3      Almagro Cluster_1
4     Almenara Cluster_1
5     Arapiles Cluster_1
6    Argüelles Cluster_1
7      Barajas Cluster_2
8  Carabanchel Cluster_1
9   Castellana Cluster_3
10    Castilla Cluster_1</code></pre>
</div>
<div class="sourceCode cell-code" id="cb45"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb45-1"><a href="#cb45-1" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(df_madrid)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  Neighbourhood Accommodates Bathrooms Bedrooms Beds Price Square.Feet
1       Acacias            3         1        1    2    45          NA
2       Acacias            2         1        1    1    50          NA
3       Acacias            6         2        3    4   100          NA
4       Acacias            2         1        0    1    39          NA
5       Acacias            6         1        2    3    60          NA
6       Acacias            2         1        1    1    75          NA
  Guests.Included Extra.People Review.Scores.Rating Latitude Longitude
1               2           10                  100 40.40404 -3.703835
2               1            0                   69 40.40221 -3.711326
3               1            0                   NA 40.40265 -3.702798
4               1            0                  100 40.40094 -3.702806
5               2           10                   88 40.40554 -3.710429
6               1            0                  100 40.40460 -3.708392
  Square.Meters neighb_id
1            NA Cluster_1
2            NA Cluster_1
3            NA Cluster_1
4            NA Cluster_1
5            NA Cluster_1
6            NA Cluster_1</code></pre>
</div>
</div>
<hr>
<ol start="12" type="1">
<li>Vamos a crear dos grupos, uno test y otro train.</li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb47"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb47-1"><a href="#cb47-1" aria-hidden="true" tabindex="-1"></a><span class="co"># 70% train y 30% test</span></span>
<span id="cb47-2"><a href="#cb47-2" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">123</span>)</span>
<span id="cb47-3"><a href="#cb47-3" aria-hidden="true" tabindex="-1"></a>idx <span class="ot">&lt;-</span> <span class="fu">sample</span>(<span class="dv">1</span><span class="sc">:</span><span class="fu">nrow</span>(df_madrid),<span class="fu">nrow</span>(df_madrid)<span class="sc">*</span><span class="fl">0.7</span>) </span>
<span id="cb47-4"><a href="#cb47-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb47-5"><a href="#cb47-5" aria-hidden="true" tabindex="-1"></a><span class="co"># df train y test</span></span>
<span id="cb47-6"><a href="#cb47-6" aria-hidden="true" tabindex="-1"></a>df_train <span class="ot">&lt;-</span> df_madrid[idx, ]</span>
<span id="cb47-7"><a href="#cb47-7" aria-hidden="true" tabindex="-1"></a>df_test <span class="ot">&lt;-</span> df_madrid[<span class="sc">-</span>idx, ]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb48"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb48-1"><a href="#cb48-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(df_train)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> Neighbourhood       Accommodates    Bathrooms        Bedrooms     
 Length:3407        Min.   : 1.0   Min.   :0.000   Min.   : 0.000  
 Class :character   1st Qu.: 3.0   1st Qu.:1.000   1st Qu.: 1.000  
 Mode  :character   Median : 4.0   Median :1.000   Median : 1.000  
                    Mean   : 4.1   Mean   :1.243   Mean   : 1.418  
                    3rd Qu.: 5.0   3rd Qu.:1.000   3rd Qu.: 2.000  
                    Max.   :16.0   Max.   :6.000   Max.   :10.000  
                                   NA's   :9       NA's   :5       
      Beds            Price         Square.Feet     Guests.Included 
 Min.   : 1.000   Min.   : 18.00   Min.   :   0.0   Min.   : 1.000  
 1st Qu.: 1.000   1st Qu.: 59.00   1st Qu.:   0.0   1st Qu.: 1.000  
 Median : 2.000   Median : 75.00   Median : 323.0   Median : 2.000  
 Mean   : 2.379   Mean   : 90.42   Mean   : 415.2   Mean   : 1.952  
 3rd Qu.: 3.000   3rd Qu.:100.00   3rd Qu.: 700.0   3rd Qu.: 2.000  
 Max.   :16.000   Max.   :800.00   Max.   :5167.0   Max.   :10.000  
 NA's   :6        NA's   :2        NA's   :3189                     
  Extra.People     Review.Scores.Rating    Latitude       Longitude     
 Min.   :  0.000   Min.   : 20.00       Min.   :40.36   Min.   :-3.761  
 1st Qu.:  0.000   1st Qu.: 88.00       1st Qu.:40.41   1st Qu.:-3.707  
 Median : 10.000   Median : 93.00       Median :40.42   Median :-3.702  
 Mean   :  8.918   Mean   : 91.53       Mean   :40.42   Mean   :-3.700  
 3rd Qu.: 15.000   3rd Qu.: 97.00       3rd Qu.:40.42   3rd Qu.:-3.697  
 Max.   :276.000   Max.   :100.00       Max.   :40.48   Max.   :-3.576  
                   NA's   :480                                          
 Square.Meters     neighb_id        
 Min.   : 22.02   Length:3407       
 1st Qu.: 44.97   Class :character  
 Median : 65.03   Mode  :character  
 Mean   : 68.28                     
 3rd Qu.: 79.99                     
 Max.   :165.00                     
 NA's   :3296                       </code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb50"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb50-1"><a href="#cb50-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(df_test)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> Neighbourhood       Accommodates     Bathrooms        Bedrooms    
 Length:1461        Min.   : 1.00   Min.   :0.000   Min.   :0.000  
 Class :character   1st Qu.: 3.00   1st Qu.:1.000   1st Qu.:1.000  
 Mode  :character   Median : 4.00   Median :1.000   Median :1.000  
                    Mean   : 4.07   Mean   :1.245   Mean   :1.418  
                    3rd Qu.: 5.00   3rd Qu.:1.000   3rd Qu.:2.000  
                    Max.   :16.00   Max.   :5.000   Max.   :5.000  
                                    NA's   :5       NA's   :2      
      Beds            Price         Square.Feet     Guests.Included 
 Min.   : 1.000   Min.   : 23.00   Min.   :   0.0   Min.   : 1.000  
 1st Qu.: 1.000   1st Qu.: 59.00   1st Qu.:   0.0   1st Qu.: 1.000  
 Median : 2.000   Median : 76.00   Median : 323.0   Median : 2.000  
 Mean   : 2.334   Mean   : 90.44   Mean   : 375.3   Mean   : 1.962  
 3rd Qu.: 3.000   3rd Qu.:100.00   3rd Qu.: 603.0   3rd Qu.: 2.000  
 Max.   :12.000   Max.   :577.00   Max.   :2153.0   Max.   :15.000  
 NA's   :2        NA's   :3        NA's   :1346                     
  Extra.People     Review.Scores.Rating    Latitude       Longitude     
 Min.   :  0.000   Min.   : 20.00       Min.   :40.36   Min.   :-3.755  
 1st Qu.:  0.000   1st Qu.: 88.00       1st Qu.:40.41   1st Qu.:-3.707  
 Median : 10.000   Median : 93.00       Median :40.42   Median :-3.702  
 Mean   :  9.279   Mean   : 91.23       Mean   :40.42   Mean   :-3.699  
 3rd Qu.: 15.000   3rd Qu.: 97.00       3rd Qu.:40.42   3rd Qu.:-3.697  
 Max.   :250.000   Max.   :100.00       Max.   :40.48   Max.   :-3.579  
                   NA's   :205                                          
 Square.Meters     neighb_id        
 Min.   : 24.99   Length:1461       
 1st Qu.: 43.01   Class :character  
 Median : 55.00   Mode  :character  
 Mean   : 62.36                     
 3rd Qu.: 72.46                     
 Max.   :140.00                     
 NA's   :1402                       </code></pre>
</div>
</div>
<hr>
<ol start="13" type="1">
<li>Tratamos de predecir los metros cuadrados en función del resto de columnas del dataframe.</li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb52"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb52-1"><a href="#cb52-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Modelo de regresión lineal</span></span>
<span id="cb52-2"><a href="#cb52-2" aria-hidden="true" tabindex="-1"></a>model <span class="ot">&lt;-</span> <span class="fu">lm</span>(Square.Meters <span class="sc">~</span> Accommodates <span class="sc">+</span> Bathrooms <span class="sc">+</span> Bedrooms <span class="sc">+</span> Price <span class="sc">+</span> Beds <span class="sc">+</span></span>
<span id="cb52-3"><a href="#cb52-3" aria-hidden="true" tabindex="-1"></a>            Guests.Included <span class="sc">+</span> Extra.People <span class="sc">+</span> Review.Scores.Rating <span class="sc">+</span> Latitude <span class="sc">+</span> Longitude,</span>
<span id="cb52-4"><a href="#cb52-4" aria-hidden="true" tabindex="-1"></a>            <span class="at">data =</span> df_train)</span>
<span id="cb52-5"><a href="#cb52-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb52-6"><a href="#cb52-6" aria-hidden="true" tabindex="-1"></a><span class="co"># Resultado</span></span>
<span id="cb52-7"><a href="#cb52-7" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = Square.Meters ~ Accommodates + Bathrooms + Bedrooms + 
    Price + Beds + Guests.Included + Extra.People + Review.Scores.Rating + 
    Latitude + Longitude, data = df_train)

Residuals:
    Min      1Q  Median      3Q     Max 
-40.203 -10.075  -2.184   8.216  55.643 

Coefficients:
                       Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)          -3.362e+03  5.268e+03  -0.638  0.52492    
Accommodates          3.500e+00  2.024e+00   1.729  0.08701 .  
Bathrooms             1.516e+01  4.744e+00   3.196  0.00189 ** 
Bedrooms              1.517e+01  3.285e+00   4.618  1.2e-05 ***
Price                 5.059e-02  2.636e-02   1.919  0.05793 .  
Beds                 -1.854e+00  2.338e+00  -0.793  0.42972    
Guests.Included      -3.691e+00  1.823e+00  -2.025  0.04564 *  
Extra.People          1.024e-01  2.174e-01   0.471  0.63880    
Review.Scores.Rating  2.566e-01  2.645e-01   0.970  0.33451    
Latitude              8.703e+01  1.258e+02   0.692  0.49054    
Longitude             4.466e+01  9.772e+01   0.457  0.64871    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 18.14 on 96 degrees of freedom
  (3300 observations deleted due to missingness)
Multiple R-squared:  0.6524,    Adjusted R-squared:  0.6162 
F-statistic: 18.02 on 10 and 96 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<hr>
<ol start="14" type="1">
<li>Mirad el histograma de los residuos sobre el conjunto de test para evaluar la calidad de vuestro modelo</li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb54"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb54-1"><a href="#cb54-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Residuos</span></span>
<span id="cb54-2"><a href="#cb54-2" aria-hidden="true" tabindex="-1"></a>residuos <span class="ot">&lt;-</span> df_test<span class="sc">$</span>Square.Meters <span class="sc">-</span> <span class="fu">predict</span>(model, <span class="at">newdata =</span> df_test)</span>
<span id="cb54-3"><a href="#cb54-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb54-4"><a href="#cb54-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Histograma</span></span>
<span id="cb54-5"><a href="#cb54-5" aria-hidden="true" tabindex="-1"></a><span class="fu">hist</span>(residuos, <span class="at">main =</span> <span class="st">"Histograma de Residuos"</span>, <span class="at">xlab =</span> <span class="st">"Residuos"</span>, <span class="at">ylab =</span> <span class="st">"Frecuencia"</span>, <span class="at">col =</span> <span class="st">"skyblue"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="Practica-Laura-Aparicio_files/figure-html/unnamed-chunk-19-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>En general, el modelo parece tener un buen ajuste. Los residuos siguen una distribución relativamente normal con una ligera asimetría. Esto es positivo, ya que sugiere que los errores están distribuidos de manera uniforme alrededor del valor medio. Variables como Bathrooms y Bedrooms son altamente significativas (p &lt; 0.01), lo que indica su influencia en los metros cuadrados. El Adjusted R-squared es 0.6162, lo que significa que el modelo explica aproximadamente el 61.62% de la variabilidad en los metros cuadrados. El p-value extremadamente bajo sugiere que el modelo en su conjunto es significativo.</p>
<hr>
<ol start="15" type="1">
<li>Si tuvieramos un anuncio de un apartamento para 6 personas (Accommodates), con 1 baño, con un precio de 80€/noche y 3 habitaciones en el barrio de Sol, con 3 camas y un review de 80. ¿Cuantos metros cuadrados tendría? Si tu modelo necesita algúna variable adicional puedes inventartela dentro del rango de valores del dataset. ¿Como varía sus metros cuadrados con cada habitación adicional?</li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb55"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb55-1"><a href="#cb55-1" aria-hidden="true" tabindex="-1"></a>new_apartment <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">Accommodates =</span> <span class="dv">6</span>,</span>
<span id="cb55-2"><a href="#cb55-2" aria-hidden="true" tabindex="-1"></a>                            <span class="at">Bathrooms =</span> <span class="dv">1</span>,</span>
<span id="cb55-3"><a href="#cb55-3" aria-hidden="true" tabindex="-1"></a>                            <span class="at">Bedrooms =</span> <span class="dv">3</span>,</span>
<span id="cb55-4"><a href="#cb55-4" aria-hidden="true" tabindex="-1"></a>                            <span class="at">Price =</span> <span class="dv">80</span>,</span>
<span id="cb55-5"><a href="#cb55-5" aria-hidden="true" tabindex="-1"></a>                            <span class="at">Beds =</span> <span class="dv">3</span>,</span>
<span id="cb55-6"><a href="#cb55-6" aria-hidden="true" tabindex="-1"></a>                            <span class="at">Guests.Included =</span> <span class="dv">6</span>,</span>
<span id="cb55-7"><a href="#cb55-7" aria-hidden="true" tabindex="-1"></a>                            <span class="at">Extra.People =</span> <span class="dv">0</span>,  </span>
<span id="cb55-8"><a href="#cb55-8" aria-hidden="true" tabindex="-1"></a>                            <span class="at">Review.Scores.Rating =</span> <span class="dv">80</span>,</span>
<span id="cb55-9"><a href="#cb55-9" aria-hidden="true" tabindex="-1"></a>                            <span class="at">Latitude =</span> <span class="fl">40.4165</span>,  <span class="co"># Asumimos una latitud dentro del rango</span></span>
<span id="cb55-10"><a href="#cb55-10" aria-hidden="true" tabindex="-1"></a>                            <span class="at">Longitude =</span> <span class="sc">-</span><span class="fl">3.7026</span>  <span class="co"># Asumimos una longitud dentro del rango</span></span>
<span id="cb55-11"><a href="#cb55-11" aria-hidden="true" tabindex="-1"></a>                            )</span>
<span id="cb55-12"><a href="#cb55-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb55-13"><a href="#cb55-13" aria-hidden="true" tabindex="-1"></a>predicted_sqm <span class="ot">&lt;-</span> <span class="fu">predict</span>(model, <span class="at">newdata =</span> new_apartment)</span>
<span id="cb55-14"><a href="#cb55-14" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"Metros cuadrados estimados:"</span>, <span class="fu">round</span>(predicted_sqm, <span class="dv">2</span>), <span class="st">"</span><span class="sc">\n</span><span class="st">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Metros cuadrados estimados: 69.2 </code></pre>
</div>
</div>
<hr>
<ol start="16" type="1">
<li>Rellenar los Square.Meters con valor NA con el estimado con el modelo anterior.</li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb57"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb57-1"><a href="#cb57-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(df_madrid)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> Neighbourhood       Accommodates      Bathrooms        Bedrooms     
 Length:4868        Min.   : 1.000   Min.   :0.000   Min.   : 0.000  
 Class :character   1st Qu.: 3.000   1st Qu.:1.000   1st Qu.: 1.000  
 Mode  :character   Median : 4.000   Median :1.000   Median : 1.000  
                    Mean   : 4.091   Mean   :1.243   Mean   : 1.418  
                    3rd Qu.: 5.000   3rd Qu.:1.000   3rd Qu.: 2.000  
                    Max.   :16.000   Max.   :6.000   Max.   :10.000  
                                     NA's   :14      NA's   :7       
      Beds            Price         Square.Feet     Guests.Included 
 Min.   : 1.000   Min.   : 18.00   Min.   :   0.0   Min.   : 1.000  
 1st Qu.: 1.000   1st Qu.: 59.00   1st Qu.:   0.0   1st Qu.: 1.000  
 Median : 2.000   Median : 75.00   Median : 323.0   Median : 2.000  
 Mean   : 2.366   Mean   : 90.43   Mean   : 401.4   Mean   : 1.955  
 3rd Qu.: 3.000   3rd Qu.:100.00   3rd Qu.: 646.0   3rd Qu.: 2.000  
 Max.   :16.000   Max.   :800.00   Max.   :5167.0   Max.   :15.000  
 NA's   :8        NA's   :5        NA's   :4535                     
  Extra.People     Review.Scores.Rating    Latitude       Longitude     
 Min.   :  0.000   Min.   : 20.00       Min.   :40.36   Min.   :-3.761  
 1st Qu.:  0.000   1st Qu.: 88.00       1st Qu.:40.41   1st Qu.:-3.707  
 Median : 10.000   Median : 93.00       Median :40.42   Median :-3.702  
 Mean   :  9.027   Mean   : 91.44       Mean   :40.42   Mean   :-3.700  
 3rd Qu.: 15.000   3rd Qu.: 97.00       3rd Qu.:40.42   3rd Qu.:-3.697  
 Max.   :276.000   Max.   :100.00       Max.   :40.48   Max.   :-3.576  
                   NA's   :685                                          
 Square.Meters     neighb_id        
 Min.   : 22.02   Length:4868       
 1st Qu.: 44.97   Class :character  
 Median : 60.02   Mode  :character  
 Mean   : 66.22                     
 3rd Qu.: 78.73                     
 Max.   :165.00                     
 NA's   :4698                       </code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb59"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb59-1"><a href="#cb59-1" aria-hidden="true" tabindex="-1"></a>df_madrid<span class="sc">$</span>Square.Meters[<span class="fu">is.na</span>(df_madrid<span class="sc">$</span>Square.Meters)] <span class="ot">&lt;-</span> <span class="fu">predict</span>(model, <span class="at">newdata =</span> df_madrid[<span class="fu">is.na</span>(df_madrid<span class="sc">$</span>Square.Meters), ])</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb60"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb60-1"><a href="#cb60-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(df_madrid)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> Neighbourhood       Accommodates      Bathrooms        Bedrooms     
 Length:4868        Min.   : 1.000   Min.   :0.000   Min.   : 0.000  
 Class :character   1st Qu.: 3.000   1st Qu.:1.000   1st Qu.: 1.000  
 Mode  :character   Median : 4.000   Median :1.000   Median : 1.000  
                    Mean   : 4.091   Mean   :1.243   Mean   : 1.418  
                    3rd Qu.: 5.000   3rd Qu.:1.000   3rd Qu.: 2.000  
                    Max.   :16.000   Max.   :6.000   Max.   :10.000  
                                     NA's   :14      NA's   :7       
      Beds            Price         Square.Feet     Guests.Included 
 Min.   : 1.000   Min.   : 18.00   Min.   :   0.0   Min.   : 1.000  
 1st Qu.: 1.000   1st Qu.: 59.00   1st Qu.:   0.0   1st Qu.: 1.000  
 Median : 2.000   Median : 75.00   Median : 323.0   Median : 2.000  
 Mean   : 2.366   Mean   : 90.43   Mean   : 401.4   Mean   : 1.955  
 3rd Qu.: 3.000   3rd Qu.:100.00   3rd Qu.: 646.0   3rd Qu.: 2.000  
 Max.   :16.000   Max.   :800.00   Max.   :5167.0   Max.   :15.000  
 NA's   :8        NA's   :5        NA's   :4535                     
  Extra.People     Review.Scores.Rating    Latitude       Longitude     
 Min.   :  0.000   Min.   : 20.00       Min.   :40.36   Min.   :-3.761  
 1st Qu.:  0.000   1st Qu.: 88.00       1st Qu.:40.41   1st Qu.:-3.707  
 Median : 10.000   Median : 93.00       Median :40.42   Median :-3.702  
 Mean   :  9.027   Mean   : 91.44       Mean   :40.42   Mean   :-3.700  
 3rd Qu.: 15.000   3rd Qu.: 97.00       3rd Qu.:40.42   3rd Qu.:-3.697  
 Max.   :276.000   Max.   :100.00       Max.   :40.48   Max.   :-3.576  
                   NA's   :685                                          
 Square.Meters       neighb_id        
 Min.   :  0.4397   Length:4868       
 1st Qu.: 48.9560   Class :character  
 Median : 54.7586   Mode  :character  
 Mean   : 62.7159                     
 3rd Qu.: 73.7419                     
 Max.   :239.7365                     
 NA's   :698                          </code></pre>
</div>
</div>
<hr>
<ol start="17" type="1">
<li>Usar PCA para encontrar el apartamento más cercano a uno dado. Este algoritmo nos ayudaría a dado un apartamento que el algoritmo nos devolvería los 5 apartamentos más similares.</li>
</ol>
<p>Crearemos una función tal que le pasemos un apartamento con los siguientes datos: * Accommodates * Bathrooms * Bedrooms * Beds * Price * Guests.Included * Extra.People * Review.Scores.Rating * Latitude * Longitude * Square.Meters</p>
<p>y nos devuelva los 5 más similares de:</p>
<p>Este ejercicio me ha vuelto loca. No paraba de darme cada vez un error diferente y he tirado de IA (a la que también se le ha hecho bola y entraba en bucle con los errores que le iba reportando). Al final conseguí crear la función y que, tal vez no el mejor, pero al menos me devuelva un resultado.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb62"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb62-1"><a href="#cb62-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Eliminar filas con valores faltantes en las características relevantes (esto lo incluyo pq me estaba dando error al ejecutar el código)</span></span>
<span id="cb62-2"><a href="#cb62-2" aria-hidden="true" tabindex="-1"></a>df_madrid_pca <span class="ot">&lt;-</span> <span class="fu">na.omit</span>(df_madrid[, <span class="fu">c</span>(<span class="st">"Accommodates"</span>, <span class="st">"Bathrooms"</span>, <span class="st">"Bedrooms"</span>, <span class="st">"Beds"</span>, <span class="st">"Price"</span>, </span>
<span id="cb62-3"><a href="#cb62-3" aria-hidden="true" tabindex="-1"></a>                                       <span class="st">"Review.Scores.Rating"</span>, <span class="st">"Latitude"</span>, <span class="st">"Longitude"</span>)])</span>
<span id="cb62-4"><a href="#cb62-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb62-5"><a href="#cb62-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Encontrar los apartamentos más similares</span></span>
<span id="cb62-6"><a href="#cb62-6" aria-hidden="true" tabindex="-1"></a>encontrar_apartamentos_similares <span class="ot">&lt;-</span> <span class="cf">function</span>(apartamento_nuevo, df_madrid_pca, <span class="at">num_vecinos =</span> <span class="dv">5</span>) {</span>
<span id="cb62-7"><a href="#cb62-7" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Características relevantes</span></span>
<span id="cb62-8"><a href="#cb62-8" aria-hidden="true" tabindex="-1"></a>  nombres_caracteristicas <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"Accommodates"</span>, <span class="st">"Bathrooms"</span>, <span class="st">"Bedrooms"</span>, <span class="st">"Beds"</span>, <span class="st">"Price"</span>, </span>
<span id="cb62-9"><a href="#cb62-9" aria-hidden="true" tabindex="-1"></a>                               <span class="st">"Review.Scores.Rating"</span>, <span class="st">"Latitude"</span>, <span class="st">"Longitude"</span>)</span>
<span id="cb62-10"><a href="#cb62-10" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Estandarizar las características del df </span></span>
<span id="cb62-11"><a href="#cb62-11" aria-hidden="true" tabindex="-1"></a>  df_escalado <span class="ot">&lt;-</span> <span class="fu">scale</span>(df_madrid_pca[nombres_caracteristicas])</span>
<span id="cb62-12"><a href="#cb62-12" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Aplicar PCA</span></span>
<span id="cb62-13"><a href="#cb62-13" aria-hidden="true" tabindex="-1"></a>  pca <span class="ot">&lt;-</span> <span class="fu">prcomp</span>(df_escalado, <span class="at">center =</span> <span class="cn">TRUE</span>)</span>
<span id="cb62-14"><a href="#cb62-14" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Preparar el apartamento nuevo para la predicción</span></span>
<span id="cb62-15"><a href="#cb62-15" aria-hidden="true" tabindex="-1"></a>  apartamento_nuevo_escalado <span class="ot">&lt;-</span> <span class="fu">scale</span>(<span class="fu">as.matrix</span>(apartamento_nuevo[nombres_caracteristicas]), <span class="at">center =</span> pca<span class="sc">$</span>center, <span class="at">scale =</span> pca<span class="sc">$</span>scale)</span>
<span id="cb62-16"><a href="#cb62-16" aria-hidden="true" tabindex="-1"></a>  <span class="fu">colnames</span>(apartamento_nuevo_escalado) <span class="ot">&lt;-</span> nombres_caracteristicas <span class="co"># (esto lo incluyo pq me estaba dando error al ejecutar el código)</span></span>
<span id="cb62-17"><a href="#cb62-17" aria-hidden="true" tabindex="-1"></a>  apartamento_nuevo_df <span class="ot">&lt;-</span> <span class="fu">as.data.frame</span>(apartamento_nuevo_escalado)</span>
<span id="cb62-18"><a href="#cb62-18" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Aplicar PCA al apartamento nuevo</span></span>
<span id="cb62-19"><a href="#cb62-19" aria-hidden="true" tabindex="-1"></a>  apartamento_nuevo_pca <span class="ot">&lt;-</span> <span class="fu">predict</span>(pca, <span class="at">newdata =</span> apartamento_nuevo_df)</span>
<span id="cb62-20"><a href="#cb62-20" aria-hidden="true" tabindex="-1"></a>  apartamento_nuevo_pca <span class="ot">&lt;-</span> apartamento_nuevo_pca[, <span class="dv">1</span><span class="sc">:</span><span class="dv">2</span>]</span>
<span id="cb62-21"><a href="#cb62-21" aria-hidden="true" tabindex="-1"></a>  <span class="co"># df PCA para los apartamentos existentes</span></span>
<span id="cb62-22"><a href="#cb62-22" aria-hidden="true" tabindex="-1"></a>  df_pca <span class="ot">&lt;-</span> <span class="fu">as.data.frame</span>(pca<span class="sc">$</span>x[, <span class="dv">1</span><span class="sc">:</span><span class="dv">2</span>])</span>
<span id="cb62-23"><a href="#cb62-23" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Distancias</span></span>
<span id="cb62-24"><a href="#cb62-24" aria-hidden="true" tabindex="-1"></a>  distancias <span class="ot">&lt;-</span> <span class="fu">sqrt</span>(<span class="fu">rowSums</span>((df_pca <span class="sc">-</span> apartamento_nuevo_pca)<span class="sc">^</span><span class="dv">2</span>))</span>
<span id="cb62-25"><a href="#cb62-25" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Índices</span></span>
<span id="cb62-26"><a href="#cb62-26" aria-hidden="true" tabindex="-1"></a>  indices_vecinos_cercanos <span class="ot">&lt;-</span> <span class="fu">order</span>(distancias)[<span class="dv">1</span><span class="sc">:</span>num_vecinos]</span>
<span id="cb62-27"><a href="#cb62-27" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Apartamentos más similares</span></span>
<span id="cb62-28"><a href="#cb62-28" aria-hidden="true" tabindex="-1"></a>  <span class="fu">return</span>(df_madrid_pca[indices_vecinos_cercanos, ])</span>
<span id="cb62-29"><a href="#cb62-29" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb62-30"><a href="#cb62-30" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb62-31"><a href="#cb62-31" aria-hidden="true" tabindex="-1"></a><span class="co"># Ejemplo </span></span>
<span id="cb62-32"><a href="#cb62-32" aria-hidden="true" tabindex="-1"></a>apartamento_nuevo <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">Accommodates =</span> <span class="dv">4</span>,</span>
<span id="cb62-33"><a href="#cb62-33" aria-hidden="true" tabindex="-1"></a>                                <span class="at">Bathrooms =</span> <span class="dv">1</span>, </span>
<span id="cb62-34"><a href="#cb62-34" aria-hidden="true" tabindex="-1"></a>                                <span class="at">Bedrooms =</span> <span class="dv">2</span>, </span>
<span id="cb62-35"><a href="#cb62-35" aria-hidden="true" tabindex="-1"></a>                                <span class="at">Beds =</span> <span class="dv">2</span>, </span>
<span id="cb62-36"><a href="#cb62-36" aria-hidden="true" tabindex="-1"></a>                                <span class="at">Price =</span> <span class="dv">100</span>, </span>
<span id="cb62-37"><a href="#cb62-37" aria-hidden="true" tabindex="-1"></a>                                <span class="at">Review.Scores.Rating =</span> <span class="dv">95</span>, </span>
<span id="cb62-38"><a href="#cb62-38" aria-hidden="true" tabindex="-1"></a>                                <span class="at">Latitude =</span> <span class="fl">40.4165</span>, </span>
<span id="cb62-39"><a href="#cb62-39" aria-hidden="true" tabindex="-1"></a>                                <span class="at">Longitude =</span> <span class="sc">-</span><span class="fl">3.7026</span>)</span>
<span id="cb62-40"><a href="#cb62-40" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb62-41"><a href="#cb62-41" aria-hidden="true" tabindex="-1"></a><span class="co"># Resultado</span></span>
<span id="cb62-42"><a href="#cb62-42" aria-hidden="true" tabindex="-1"></a>apartamentos_similares <span class="ot">&lt;-</span> <span class="fu">encontrar_apartamentos_similares</span>(apartamento_nuevo, df_madrid_pca, <span class="dv">5</span>)</span>
<span id="cb62-43"><a href="#cb62-43" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(apartamentos_similares)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>     Accommodates Bathrooms Bedrooms Beds Price Review.Scores.Rating Latitude
855            16       3.0        7   16   550                   82 40.41631
1856           16       5.0        5   13   365                   98 40.41826
1900           14       5.0        5   10   500                  100 40.42340
4060           10       4.5        5    8   600                  100 40.42501
3807           11       4.0        6    9   450                  100 40.41989
     Longitude
855  -3.700803
1856 -3.690208
1900 -3.695154
4060 -3.687864
3807 -3.708749</code></pre>
</div>
</div>
<hr>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->



</body></html>